/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import TCP.IndividuoTCP;
import TCP_Hibrido.IndividuoTCP_Hibrido;
import TRESSAT.Individuo3SAT;

/**
 *
 * @author skabe
 */
public class JPanel_Individuos extends javax.swing.JPanel {

    private Individuo3SAT individuo3SAT=null;
    private IndividuoTCP individuoTCP=null;
    private IndividuoTCP_Hibrido individuoTCPHibrido=null;
    public JPanel_Individuos(Individuo3SAT indiv) {
        initComponents();
        this.jTextField_Fitness.setText("Fitness: "+indiv.getFitness());
        this.jTextField_Fitness.setToolTipText(indiv.toString());
        this.individuo3SAT=indiv;
    }

    public JPanel_Individuos(IndividuoTCP indiv) {
        initComponents();
        this.jTextField_Fitness.setText("Fitness: "+indiv.getFitness()+"");
        this.jTextField_Fitness.setToolTipText(indiv.toString());
        this.individuoTCP=indiv;
    }

    public JPanel_Individuos(IndividuoTCP_Hibrido indiv) {
        initComponents();
        this.jTextField_Fitness.setText("Fitness: "+indiv.getFitness()+"");
        this.jTextField_Fitness.setToolTipText(indiv.toString());
        this.individuoTCPHibrido=indiv;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox_Indiv = new javax.swing.JCheckBox();
        jTextField_Fitness = new javax.swing.JTextField();

        jCheckBox_Indiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_IndivActionPerformed(evt);
            }
        });

        jTextField_Fitness.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox_Indiv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Fitness, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox_Indiv)
                    .addComponent(jTextField_Fitness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_IndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_IndivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_IndivActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox_Indiv;
    private javax.swing.JTextField jTextField_Fitness;
    // End of variables declaration//GEN-END:variables

    public boolean isSelected(){
        return jCheckBox_Indiv.isSelected();
    }
    public Object getIndividuo(){
        if(individuo3SAT!=null){
            return individuo3SAT;
        }else if(individuoTCP!=null){
            return individuoTCP;
        }else if(individuoTCPHibrido!=null){
            return individuoTCPHibrido;
        }
        return null;
    }
}
